### PR TITLE
update rates.json until 240418

### PR DESCRIPTION
**Pull request by lbarjak**

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmintsim* ready!

Built with commit 910d00fe262db4fdd64e247893b178444e2842be

https://deploy-preview-93--augmintsim.netlify.com

**Review by szerintedmi — CHANGES_REQUESTED** [review]
@lbarjak : you closed your other PR (#79 ) where I requested changes. This PR contains the same changeset, we lost my comments from that PR and those changes haven't been implemented.
Would you please check my comments on #79 ?

**Comment by lbarjak** [comment]
I wanted to send 'rates.json until 240418' separately

**Comment by szerintedmi** [comment]
this contains graph refresh interval changes too which outdated, #115 has proper solution for refresh graph interval

**Pull request closed without merging**
